import type { Metadata } from "next";
import "./styles/global.css";
import "./styles/common.css";
import { Poppins, Inter as FontSans } from "next/font/google";
import Provider from "./providers";
import cn from "@/core/utils/cn";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";

export const metadata: Metadata = {
  title: "Gable - Job Portal",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(poppins.className, fontSans.variable, poppins.variable)}
      >
        <Provider>
          <Header />
          <div className="">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
